spring:
  application:
    name: Backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/optilab}
    username: ${DATABASE_USERNAME:optilab}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      connect-timeout: 2s
      timeout: 2s